#!/bin/sh

BASEIMAGE=swc.registry.benzaiten.toshiba.co.jp/db/pgspider/pgspider:latest
DOCKERFILE=Dockerfile_install_fdws
IMAGE_NAME=optimized_pgspider

SQLITE_FDW_PACKAGE_NAME="sqlite_fdw_16-2.4.0-rhel8.x86_64.rpm"
SQLITE_FDW_URL_PACKAGE="https://tccloud2.toshiba.co.jp/swc/gitlab/api/v4/projects/541/packages/generic/rpm_RL8/16.0/sqlite_fdw_16-2.4.0-rhel8.x86_64.rpm"
SQLITE_FDW_ACCESS_TOKEN=ACCESS_TOKEN
SQLITE_FDW_RELEASE_VERSION="2.4.0"

TINYBRACE_FDW_PACKAGE_NAME=
TINYBRACE_FDW_URL_PACKAGE=
TINYBRACE_FDW_ACCESS_TOKEN=
TINYBRACE_FDW_RELEASE_VERSION=

SQLUMDASH_FDW_PACKAGE_NAME=
SQLUMDASH_FDW_URL_PACKAGE=
SQLUMDASH_FDW_ACCESS_TOKEN=
SQLUMDASH_FDW_RELEASE_VERSION=

MYSQL_FDW_PACKAGE_NAME=
MYSQL_FDW_URL_PACKAGE=
MYSQL_FDW_ACCESS_TOKEN=
MYSQL_FDW_RELEASE_VERSION=

INFLUXDB_CXX_PACKAGE_NAME="influxdb-cxx-0.0.1-rhel8.x86_64.rpm"
INFLUXDB_CXX_URL_PACKAGE="URL/influxdb-cxx-0.0.1-rhel8.x86_64.rpm"
INFLUXDB_CXX_ACCESS_TOKEN=ACCESS_TOKEN

INFLUXDB_FDW_PACKAGE_NAME="influxdb_fdw_16-2.0.0-rhel8.x86_64.rpm"
INFLUXDB_FDW_URL_PACKAGE="URL/influxdb_fdw_16-2.0.0-rhel8.x86_64.rpm"
INFLUXDB_FDW_ACCESS_TOKEN=ACCESS_TOKEN
INFLUXDB_FDW_RELEASE_VERSION="2.1.0"

GRIDDB_FDW_PACKAGE_NAME=
GRIDDB_FDW_URL_PACKAGE=
GRIDDB_FDW_ACCESS_TOKEN=
GRIDDB_FDW_RELEASE_VERSION="2.3.0"

AWS_S3_CPP_PACKAGE_NAME=aws_s3_cpp-1.11.9-rhel8.x86_64.rpm
AWS_S3_CPP_URL_PACKAGE="URL/aws_s3_cpp-1.11.9-rhel8.x86_64.rpm"
AWS_S3_CPP_ACCESS_TOKEN=ACCESS_TOKEN

ARROW_PACKAGE_NAME=arrow-12.0.0-rhel8.x86_64.rpm
ARROW_URL_PACKAGE="URL/arrow-12.0.0-rhel8.x86_64.rpm"
ARROW_ACCESS_TOKEN=ACCESS_TOKEN

PARQUET_S3_FDW_PACKAGE_NAME=parquet_s3_fdw_16-1.0.0-rhel8.x86_64.rpm
PARQUET_S3_FDW_URL_PACKAGE="URL/parquet_s3_fdw_16-1.0.0-rhel8.x86_64.rpm"
PARQUET_S3_FDW_ACCESS_TOKEN=ACCESS_TOKEN
PATQUET_S3_FDW_RELEASE_VERSION="1.1.0"

DYNAMODB_FDW_PACKAGE_NAME=
DYNAMODB_FDW_URL_PACKAGE=
DYNAMODB_FDW_ACCESS_TOKEN=
DYNAMODB_FDW_RELEASE_VERSION=

MONGO_FDW_PACKAGE_NAME=
MONGO_FDW_URL_PACKAGE=
MONGO_FDW_ACCESS_TOKEN=
MONGO_FDW_RELEASE_VERSION=

ODBC_FDW_PACKAGE_NAME=
ODBC_FDW_URL_PACKAGE=
ODBC_FDW_ACCESS_TOKEN=
ODBC_FDW_RELEASE_VERSION=

JDBC_FDW_PACKAGE_NAME=
JDBC_FDW_URL_PACKAGE=
JDBC_FDW_ACCESS_TOKEN=
JDBC_FDW_RELEASE_VERSION=

POSTGREST_FDW_PACKAGE_NAME=
POSTGREST_FDW_URL_PACKAGE=
POSTGREST_FDW_ACCESS_TOKEN=
POSTGREST_FDW_RELEASE_VERSION=

OBJSTORAGE_FDW_PACKAGE_NAME=
OBJSTORAGE_FDW_URL_PACKAGE=
OBJSTORAGE_FDW_ACCESS_TOKEN=
OBJSTORAGE_FDW_RELEASE_VERSION=

PGSPIDER_EXT_PACKAGE_NAME=
PGSPIDER_EXT_URL_PACKAGE=
PGSPIDER_EXT_ACCESS_TOKEN=
PGSPIDER_EXT_FDW_RELEASE_VERSION=

GITLAB_FDW_PACKAGE_NAME=
GITLAB_FDW_URL_PACKAGE=
GITLAB_FDW_ACCESS_TOKEN=
GITLAB_FDW_RELEASE_VERSION=

REDMINE_FDW_PACKAGE_NAME=
REDMINE_FDW_URL_PACKAGE=
REDMINE_FDW_ACCESS_TOKEN=
REDMINE_FDW_RELEASE_VERSION=


set -eE

# User need to specified proxy and no_proxy as environment variable before executing
#   Example:
#       export proxy=http://username:password@proxy:port
#       export no_proxy=127.0.0.1,localhost
if [[ -z "${proxy}" ]]; then
  echo "proxy environment variable not set"
  exit 1
fi

if [[ -z "${no_proxy}" ]]; then
  echo "no_proxy environment variable not set"
  exit 1
fi

docker build -t ${IMAGE_NAME} \
        --build-arg proxy=${proxy} \
        --build-arg no_proxy=${no_proxy} \
        --build-arg baseimage=${BASEIMAGE} \
        --build-arg SQLITE_FDW_PACKAGE_NAME=${SQLITE_FDW_PACKAGE_NAME} \
        --build-arg SQLITE_FDW_URL_PACKAGE=${SQLITE_FDW_URL_PACKAGE} \
        --build-arg SQLITE_FDW_ACCESS_TOKEN=${SQLITE_FDW_ACCESS_TOKEN} \
        --build-arg SQLITE_FDW_RELEASE_VERSION=${SQLITE_FDW_RELEASE_VERSION} \
        --build-arg TINYBRACE_FDW_PACKAGE_NAME=${TINYBRACE_FDW_PACKAGE_NAME} \
        --build-arg TINYBRACE_FDW_URL_PACKAGE=${TINYBRACE_FDW_URL_PACKAGE} \
        --build-arg TINYBRACE_FDW_ACCESS_TOKEN=${TINYBRACE_FDW_ACCESS_TOKEN} \
        --build-arg TINYBRACE_FDW_RELEASE_VERSION=${TINYBRACE_FDW_RELEASE_VERSION} \
        --build-arg SQLUMDASH_FDW_PACKAGE_NAME=${SQLUMDASH_FDW_PACKAGE_NAME} \
        --build-arg SQLUMDASH_FDW_URL_PACKAGE=${SQLUMDASH_FDW_URL_PACKAGE} \
        --build-arg SQLUMDASH_FDW_ACCESS_TOKEN=${SQLUMDASH_FDW_ACCESS_TOKEN} \
        --build-arg SQLUMDASH_FDW_RELEASE_VERSION=${SQLUMDASH_FDW_RELEASE_VERSION} \
        --build-arg MYSQL_FDW_PACKAGE_NAME=${MYSQL_FDW_PACKAGE_NAME} \
        --build-arg MYSQL_FDW_URL_PACKAGE=${MYSQL_FDW_URL_PACKAGE} \
        --build-arg MYSQL_FDW_ACCESS_TOKEN=${MYSQL_FDW_ACCESS_TOKEN} \
        --build-arg MYSQL_FDW_RELEASE_VERSION=${MYSQL_FDW_RELEASE_VERSION} \
        --build-arg INFLUXDB_CXX_PACKAGE_NAME=${INFLUXDB_CXX_PACKAGE_NAME} \
        --build-arg INFLUXDB_CXX_URL_PACKAGE=${INFLUXDB_CXX_URL_PACKAGE} \
        --build-arg INFLUXDB_CXX_ACCESS_TOKEN=${INFLUXDB_CXX_ACCESS_TOKEN} \
        --build-arg INFLUXDB_FDW_PACKAGE_NAME=${INFLUXDB_FDW_PACKAGE_NAME} \
        --build-arg INFLUXDB_FDW_URL_PACKAGE=${INFLUXDB_FDW_URL_PACKAGE} \
        --build-arg INFLUXDB_FDW_ACCESS_TOKEN=${INFLUXDB_FDW_ACCESS_TOKEN} \
        --build-arg INFLUXDB_FDW_RELEASE_VERSION=${INFLUXDB_FDW_RELEASE_VERSION} \
        --build-arg GRIDDB_FDW_PACKAGE_NAME=${GRIDDB_FDW_PACKAGE_NAME} \
        --build-arg GRIDDB_FDW_URL_PACKAGE=${GRIDDB_FDW_URL_PACKAGE} \
        --build-arg GRIDDB_FDW_ACCESS_TOKEN=${GRIDDB_FDW_ACCESS_TOKEN} \
        --build-arg GRIDDB_FDW_RELEASE_VERSION=${GRIDDB_FDW_RELEASE_VERSION} \
        --build-arg AWS_S3_CPP_PACKAGE_NAME=${AWS_S3_CPP_PACKAGE_NAME} \
        --build-arg AWS_S3_CPP_URL_PACKAGE=${AWS_S3_CPP_URL_PACKAGE} \
        --build-arg AWS_S3_CPP_ACCESS_TOKEN=${AWS_S3_CPP_ACCESS_TOKEN} \
        --build-arg ARROW_PACKAGE_NAME=${ARROW_PACKAGE_NAME} \
        --build-arg ARROW_URL_PACKAGE=${ARROW_URL_PACKAGE} \
        --build-arg ARROW_ACCESS_TOKEN=${ARROW_ACCESS_TOKEN} \
        --build-arg PARQUET_S3_FDW_PACKAGE_NAME=${PARQUET_S3_FDW_PACKAGE_NAME} \
        --build-arg PARQUET_S3_FDW_URL_PACKAGE=${PARQUET_S3_FDW_URL_PACKAGE} \
        --build-arg PARQUET_S3_FDW_ACCESS_TOKEN=${PARQUET_S3_FDW_ACCESS_TOKEN} \
        --build-arg PATQUET_S3_FDW_RELEASE_VERSION=${PATQUET_S3_FDW_RELEASE_VERSION} \
        --build-arg DYNAMODB_FDW_PACKAGE_NAME=${DYNAMODB_FDW_PACKAGE_NAME} \
        --build-arg DYNAMODB_FDW_URL_PACKAGE=${DYNAMODB_FDW_URL_PACKAGE} \
        --build-arg DYNAMODB_FDW_ACCESS_TOKEN=${DYNAMODB_FDW_ACCESS_TOKEN} \
        --build-arg DYNAMODB_FDW_RELEASE_VERSION=${DYNAMODB_FDW_RELEASE_VERSION} \
        --build-arg MONGO_FDW_PACKAGE_NAME=${MONGO_FDW_PACKAGE_NAME} \
        --build-arg MONGO_FDW_URL_PACKAGE=${MONGO_FDW_URL_PACKAGE} \
        --build-arg MONGO_FDW_ACCESS_TOKEN=${MONGO_FDW_ACCESS_TOKEN} \
        --build-arg MONGO_FDW_RELEASE_VERSION=${MONGO_FDW_RELEASE_VERSION} \
        --build-arg ODBC_FDW_PACKAGE_NAME=${ODBC_FDW_PACKAGE_NAME} \
        --build-arg ODBC_FDW_URL_PACKAGE=${ODBC_FDW_URL_PACKAGE} \
        --build-arg ODBC_FDW_ACCESS_TOKEN=${ODBC_FDW_ACCESS_TOKEN} \
        --build-arg ODBC_FDW_RELEASE_VERSION=${ODBC_FDW_RELEASE_VERSION} \
        --build-arg JDBC_FDW_PACKAGE_NAME=${JDBC_FDW_PACKAGE_NAME} \
        --build-arg JDBC_FDW_URL_PACKAGE=${JDBC_FDW_URL_PACKAGE} \
        --build-arg JDBC_FDW_ACCESS_TOKEN=${JDBC_FDW_ACCESS_TOKEN} \
        --build-arg JDBC_FDW_RELEASE_VERSION=${JDBC_FDW_RELEASE_VERSION} \
        --build-arg POSTGREST_FDW_PACKAGE_NAME=${POSTGREST_FDW_PACKAGE_NAME} \
        --build-arg POSTGREST_FDW_URL_PACKAGE=${POSTGREST_FDW_URL_PACKAGE} \
        --build-arg POSTGREST_FDW_ACCESS_TOKEN=${POSTGREST_FDW_ACCESS_TOKEN} \
        --build-arg POSTGREST_FDW_RELEASE_VERSION=${POSTGREST_FDW_RELEASE_VERSION} \
        --build-arg OBJSTORAGE_FDW_PACKAGE_NAME=${OBJSTORAGE_FDW_PACKAGE_NAME} \
        --build-arg OBJSTORAGE_FDW_URL_PACKAGE=${OBJSTORAGE_FDW_URL_PACKAGE} \
        --build-arg OBJSTORAGE_FDW_ACCESS_TOKEN=${OBJSTORAGE_FDW_ACCESS_TOKEN} \
        --build-arg OBJSTORAGE_FDW_RELEASE_VERSION=${OBJSTORAGE_FDW_RELEASE_VERSION} \
        --build-arg PGSPIDER_EXT_PACKAGE_NAME=${PGSPIDER_EXT_PACKAGE_NAME} \
        --build-arg PGSPIDER_EXT_URL_PACKAGE=${PGSPIDER_EXT_URL_PACKAGE} \
        --build-arg PGSPIDER_EXT_ACCESS_TOKEN=${PGSPIDER_EXT_ACCESS_TOKEN} \
        --build-arg PGSPIDER_EXT_FDW_RELEASE_VERSION=${PGSPIDER_EXT_FDW_RELEASE_VERSION} \
        --build-arg GITLAB_FDW_PACKAGE_NAME=${GITLAB_FDW_PACKAGE_NAME} \
        --build-arg GITLAB_FDW_URL_PACKAGE=${GITLAB_FDW_URL_PACKAGE} \
        --build-arg GITLAB_FDW_ACCESS_TOKEN=${GITLAB_FDW_ACCESS_TOKEN} \
        --build-arg GITLAB_FDW_RELEASE_VERSION=${GITLAB_FDW_RELEASE_VERSION} \
        --build-arg REDMINE_FDW_PACKAGE_NAME=${REDMINE_FDW_PACKAGE_NAME} \
        --build-arg REDMINE_FDW_URL_PACKAGE=${REDMINE_FDW_URL_PACKAGE} \
        --build-arg REDMINE_FDW_ACCESS_TOKEN=${REDMINE_FDW_ACCESS_TOKEN} \
        --build-arg REDMINE_FDW_RELEASE_VERSION=${REDMINE_FDW_RELEASE_VERSION} \
        -f ${DOCKERFILE} .
