CREATE EXTENSION pgspider_core_fdw;
CREATE SERVER pgspider_svr FOREIGN DATA WRAPPER pgspider_core_fdw OPTIONS (host '127.0.0.1',port '50849');
CREATE USER mapping for public server pgspider_svr OPTIONS(user 'postgres',password 'postgres');
CREATE FOREIGN TABLE test1 (i int) SERVER pgspider_svr;
SELECT * FROM test1;
SELECT * FROM test1 UNDER '/test2/';
CREATE EXTENSION postgres_fdw;
CREATE EXTENSION file_fdw;
CREATE EXTENSION sqlite_fdw;
CREATE EXTENSION tinybrace_fdw;
CREATE EXTENSION mysql_fdw;
CREATE SERVER file_svr FOREIGN DATA WRAPPER file_fdw;
CREATE SERVER filesvr2 FOREIGN DATA WRAPPER file_fdw;
CREATE FOREIGN TABLE test1__file_svr__0 (i int) SERVER file_svr options(filename '/tmp/pgtest.csv');
SELECT * FROM test1;
CREATE FOREIGN TABLE test1__filesvr2__0 (i int) SERVER file_svr options(filename '/tmp/pgtest.csv');
SELECT * FROM test1 order by i;
SELECT * FROM test1 UNDER '/file_svr/';
SELECT * FROM test1 under '/file_svr/' where i = 1;
CREATE SERVER tiny_svr FOREIGN DATA WRAPPER tinybrace_fdw OPTIONS (host '127.0.0.1',port '5100', dbname 'test.db');
CREATE USER mapping for public server tiny_svr OPTIONS(username 'user',password 'testuser');
CREATE FOREIGN TABLE test1__tiny_svr__0 (i int) SERVER tiny_svr OPTIONS(table_name 'test1');
SELECT * FROM test1__tiny_svr__0;
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/tiny_svr/';
SELECT * FROM test1 under '/tiny_svr/' where i = 1;
CREATE SERVER post_svr FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '127.0.0.1',port '15432');
CREATE USER mapping for public server post_svr OPTIONS(user 'postgres',password 'postgres');
CREATE FOREIGN TABLE test1__post_svr__0 (i int) SERVER post_svr OPTIONS(table_name 'test1');
SELECT * FROM test1__post_svr__0;
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/post_svr/';
SELECT * FROM test1 under '/post_svr/' where i = 1;
CREATE SERVER sqlite_svr FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/tmp/pgtest.db');
CREATE FOREIGN TABLE test1__sqlite_svr__0 (i int) SERVER sqlite_svr OPTIONS(table 'test1');
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/sqlite_svr/';
SELECT * FROM test1 under '/sqlite_svr/' where i = 4;
CREATE SERVER mysql_svr FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host '127.0.0.1',port '3306');
CREATE USER mapping for public server mysql_svr OPTIONS(username 'root',password 'mysql');
CREATE FOREIGN TABLE test1__mysql_svr__0 (i int) SERVER mysql_svr OPTIONS(dbname 'test',table_name 'test1');
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/mysql_svr/';
SELECT * FROM test1 where i = 1;
SELECT * FROM test1 under '/mysql_svr/' where i = 5;
DROP USER MAPPING FOR public SERVER pgspider_svr;
DROP FOREIGN TABLE test1;
DROP SERVER pgspider_svr;
DROP EXTENSION pgspider_core_fdw;
CREATE EXTENSION pgspider_core_fdw;
CREATE SERVER pgspider_svr FOREIGN DATA WRAPPER pgspider_core_fdw OPTIONS (host '127.0.0.1',port '50849');
CREATE USER mapping for public server pgspider_svr OPTIONS(user 'postgres',password 'postgres');
CREATE FOREIGN TABLE test1 (i int) SERVER pgspider_svr;
SELECT * FROM test1;
SELECT * FROM test1 UNDER '/test2/';
CREATE EXTENSION postgres_fdw;
CREATE EXTENSION file_fdw;
CREATE EXTENSION sqlite_fdw;
CREATE EXTENSION tinybrace_fdw;
CREATE EXTENSION mysql_fdw;
CREATE SERVER file_svr FOREIGN DATA WRAPPER file_fdw;
CREATE SERVER filesvr2 FOREIGN DATA WRAPPER file_fdw;
CREATE FOREIGN TABLE test1__file_svr__0 (i int) SERVER file_svr options(filename '/tmp/pgtest.csv');
SELECT * FROM test1;
CREATE FOREIGN TABLE test1__filesvr2__0 (i int) SERVER file_svr options(filename '/tmp/pgtest.csv');
SELECT * FROM test1 order by i;
SELECT * FROM test1 UNDER '/file_svr/';
SELECT * FROM test1 under '/file_svr/' where i = 1;
CREATE SERVER tiny_svr FOREIGN DATA WRAPPER tinybrace_fdw OPTIONS (host '127.0.0.1',port '5100', dbname 'test.db');
CREATE USER mapping for public server tiny_svr OPTIONS(username 'user',password 'testuser');
CREATE FOREIGN TABLE test1__tiny_svr__0 (i int) SERVER tiny_svr OPTIONS(table_name 'test1');
SELECT * FROM test1__tiny_svr__0;
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/tiny_svr/';
SELECT * FROM test1 under '/tiny_svr/' where i = 1;
CREATE SERVER post_svr FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '127.0.0.1',port '15432');
CREATE USER mapping for public server post_svr OPTIONS(user 'postgres',password 'postgres');
CREATE FOREIGN TABLE test1__post_svr__0 (i int) SERVER post_svr OPTIONS(table_name 'test1');
SELECT * FROM test1__post_svr__0;
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/post_svr/';
SELECT * FROM test1 under '/post_svr/' where i = 1;
CREATE SERVER sqlite_svr FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/tmp/pgtest.db');
CREATE FOREIGN TABLE test1__sqlite_svr__0 (i int) SERVER sqlite_svr OPTIONS(table 'test1');
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/sqlite_svr/';
SELECT * FROM test1 under '/sqlite_svr/' where i = 4;
CREATE SERVER mysql_svr FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host '127.0.0.1',port '3306');
CREATE USER mapping for public server mysql_svr OPTIONS(username 'root',password 'mysql');
CREATE FOREIGN TABLE test1__mysql_svr__0 (i int) SERVER mysql_svr OPTIONS(dbname 'test',table_name 'test1');
SELECT * FROM test1 ORDER BY i;
SELECT * FROM test1 UNDER '/mysql_svr/';
SELECT * FROM test1 where i = 1;
SELECT * FROM test1 under '/mysql_svr/' where i = 5;
DROP USER MAPPING FOR public SERVER pgspider_svr;
DROP FOREIGN TABLE test1;
DROP SERVER pgspider_svr;
DROP EXTENSION pgspider_core_fdw;
