services:

  minio:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: "no"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.26.0
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data
    command: azurite-blob --blobHost 0.0.0.0
    restart: "no"

  gcs:
    image: fsouza/fake-gcs-server:1.47
    ports:
      - "4443:4443"
    volumes:
      - gcs-data:/data
    command: -scheme http
    restart: "no"

  minio2:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data2:/data
    command: server /data --console-address ":9001"
    restart: "no"

  azurite2:
    image: mcr.microsoft.com/azure-storage/azurite:3.26.0
    ports:
      - "10010:10000"
    volumes:
      - azurite-data2:/data
    command: azurite-blob --blobHost 0.0.0.0
    restart: "no"

  gcs2:
    image: fsouza/fake-gcs-server:1.47
    ports:
      - "4453:4443"
    volumes:
      - gcs-data2:/data
    command: -scheme http
    restart: "no"

volumes:
  minio-data:
  azurite-data:
  gcs-data:
  minio-data2:
  azurite-data2:
  gcs-data2:
